### ISSUE TITLE
Can't see my html file in my browser

### ISSUE THREAD

**Issue by askaalyy** [askaalyy/dinosaur-designs#2]
Can't see my html file in my browser @carolsinc

**Comment by carolsinc** [comment]
This is a small thing but your background colour is missing the closing ; in your css

**Comment by askaalyy** [comment]
ohh thank u! the image is not showing up...

**Comment by carolsinc** [comment]
you need to include the .jpg or .svg

**Comment by askaalyy** [comment]
lol forgot that. 
do u know what: element figcaption not allowed as child of element main in this context mean?

**Comment by carolsinc** [comment]
your omg and fig caption need to go inside a figure tag

**Comment by carolsinc** [comment]
your *img not omg lol

**Comment by askaalyy** [comment]
ohhhh I swear I cant even copy code properly 😆 thanks for all ur help!!
