### ISSUE TITLE
css h1 

### ISSUE THREAD

**Issue by askaalyy** [askaalyy/dinosaur-designs#3]
Hi! 

on my marbot it keeps saying " line 16 expected to see font-family inside h1 in CSS? but on the webpage where I am following along it doesn't have other elements inside the header?

@carolsinc

**Comment by carolsinc** [comment]
You shouldn't have h3 or h4 on this site, they are all h2. It is asking you to put a font-family on your h1 because it is a different font than the rest of the website

**Comment by askaalyy** [comment]
ohhh thank u, it makes sense now
